// This file emulates the file that would normally be created by Bison
// This file would normally be generated by Bison

#include <stdio.h>
#include <stdlib.h>
#include "types.h"
#include "functions.h"
#include "calc.tab.h"

FILE *yyin = NULL;
char *yytext = NULL;

FlowNode* acceptingState( TokenType end_state ){
    FlowNode* final = (FlowNode*) malloc( sizeof( FlowNode ));
    final->state = end_state;
    final->arraySize = 0;
    final->transitions = NULL;
    return final;
}

FlowNode* init_ID(){
    int PATHS = 1;
    FlowNode* R = (FlowNode*) malloc( sizeof( FlowNode ));
    R->state = BAD;
    R->arraySize = PATHS;

    R->transitions = (FunctionNodePair*) malloc( sizeof(FunctionNodePair) * PATHS );
    (R->transitions+0)->transition = &isDigit;
    (R->transitions+0)->nextNode = acceptingState( ID );

    return R;
}

FlowNode* initializeTree(){
    int PATHS = 1;
    FlowNode* root = (FlowNode*) malloc( sizeof( FlowNode) );
    root->state = BAD;
    root->arraySize = PATHS;

    root->transitions = (FunctionNodePair*) malloc( sizeof(FunctionNodePair) * PATHS );
    (root->transitions+0)->transition = &isCharacter_R;
    (root->transitions+0)->nextNode = init_ID();

    return root;
}

void destroyTree(FlowNode* root){
    int i;
    for (i = 0; i < root->arraySize; ++i ){
        destroyTree((root->transitions + i)->nextNode);
        (root->transitions + i)->nextNode = NULL;
    }
    free( root->transitions );
    root->transitions = NULL;
    free( root );
    root = NULL;
}

// TODO modify to use the string representation of token and have the token type
// be the enum TokenType
int ExportToken(FILE *yyout, TokenType token, char *yytext)
{
    fprintf(yyout, "<%s> %s\n", toString(token), ((yytext)? yytext:""));
    if (yytext)
       free(yytext);
    yytext = NULL;
    return 0;
}

int yyparse(char const *filename)
{
   FILE *yyout;
   TokenType token;
   FlowNode* root = initializeTree();

   //initialize current to an empty string
   char* current = (char*) malloc(sizeof(char));
   *current = '\0';
   
   yyin = fopen(filename, "rt");
   if (!yyin)
   {
      printf("File %s failed to open.\n", filename);
      return -1;
   }

   yyout = fopen(OUTPUTFILE, "wt");
   if (!yyout)
   {
      printf("File %s failed to open.\n", OUTPUTFILE);
      return -2;
   }

   while ((token=yylex(root, &current)) != END)
       ExportToken(yyout, token, yytext);
   ExportToken(yyout, token, yytext);

   destroyTree( root );
   free( current );
   
   fclose(yyin);
   fclose(yyout);
   
   return 0;
}

