// This file emulates the file that would normally be created by Bison
// This file would normally be generated by Bison

#include <stdio.h>
#include <stdlib.h>
#include "types.h"
#include "functions.h"
#include "calc.tab.h"

FILE *yyin = NULL;
char *yytext = NULL;

FlowNode* initNode(int paths, TokenType state){
    FlowNode* R = (FlowNode*) malloc( sizeof( FlowNode ));
    R->state = state;
    R->arraySize = paths;
    R->transitions = (FunctionNodePair*) malloc( sizeof(FunctionNodePair) * paths );
    // !NOTE! the transitions are not initializaed
    return R;
}

FlowNode* acceptingState( TokenType end_state ){
    FlowNode* final = (FlowNode*) malloc( sizeof( FlowNode ));
    final->state = end_state;
    final->arraySize = 0;
    final->transitions = NULL;
    return final;
}

FlowNode* init_ID(){
    FlowNode* R = initNode( 1, BAD );
    (R->transitions+0)->transition = &isDigit;
    (R->transitions+0)->nextNode = acceptingState( ID );
    return R;
}

FlowNode* init_BAD() {
    FlowNode* R = initNode( 1, BAD );
    (R->transitions+0)->transition = &notStart;
    (R->transitions+0)->nextNode = R;
    return R;
}

FlowNode* initializeTree(){
    FlowNode* root = initNode( 3, BAD );

    (root->transitions+0)->transition = &isCharacter_R;
    (root->transitions+0)->nextNode = init_ID();

    (root->transitions+1)->transition = &isCharacter_EOF;
    (root->transitions+1)->nextNode = acceptingState( END );

    (root->transitions+2)->transition = &notStart;
    (root->transitions+2)->nextNode = init_BAD();

    return root;
}

void destroyTree(FlowNode* root){
    int i;
    for (i = 0; i < root->arraySize; ++i ){
        // handle recursive
        if (( root->transitions + i )->nextNode == root ){
            // don't do anything because it will get handled soon
        } else {
            destroyTree((root->transitions + i)->nextNode);
        }
        (root->transitions + i)->nextNode = NULL;
    }
    free( root->transitions );
    root->transitions = NULL;
    free( root );
    root = NULL;
}

// TODO modify to use the string representation of token and have the token type
// be the enum TokenType
int ExportToken(FILE *yyout, TokenType token, char *yytext)
{
    fprintf(yyout, "<%s> %s\n", toString(token), ((yytext)? yytext:""));
    if (yytext)
       free(yytext);
    yytext = NULL;
    return 0;
}

int yyparse(char const *filename)
{
   FILE *yyout;
   TokenType token;
   FlowNode* root = initializeTree();

   //initialize current to an empty string
   char* current = (char*) malloc(sizeof(char));
   *current = '\0';
   
   yyin = fopen(filename, "rt");
   if (!yyin)
   {
      printf("File %s failed to open.\n", filename);
      return -1;
   }

   yyout = fopen(OUTPUTFILE, "wt");
   if (!yyout)
   {
      printf("File %s failed to open.\n", OUTPUTFILE);
      return -2;
   }

   while ((token=yylex(root, &current)) != END)
       ExportToken(yyout, token, yytext);
   ExportToken(yyout, token, yytext);

   free( current );
   
   fclose(yyin);
   fclose(yyout);
   destroyTree( root );
   return 0;
}

